/**
 * Integration tests for formatter validation
 *
 * Tests that the formatter correctly validates amounts before formatting
 * and preserves original lines when validation fails.
 *
 * Note: Diagnostics are now generated by the Validator class (see validator.test.ts).
 * These tests verify that the formatter preserves unsafe lines.
 */

import { FormattingProvider } from '../../src/features/formatter';
import { parser } from '../../src/parser';
import { TextDocument } from 'vscode-languageserver-textdocument';

describe('Formatter Validation Integration', () => {
  const provider = new FormattingProvider();

  const createDocument = (content: string): TextDocument => {
    return TextDocument.create('file:///test.journal', 'hledger', 1, content);
  };

  describe('format mismatch detection', () => {
    it('should skip formatting when decimal marks do not match', () => {
      const content = `commodity EUR
    format 1.000,00

2024-01-01 Test
    expenses:food    EUR 100.50
    assets:checking
`;
      const doc = createDocument(content);
      const parsed = parser.parse(doc);
      const edits = provider.formatDocument(doc, parsed, { tabSize: 2, insertSpaces: true });

      const formatted = edits[0].newText;
      const lines = formatted.split('\n');

      // The EUR line should be preserved as-is (not reformatted)
      // because it uses . as decimal mark instead of ,
      expect(lines[4]).toContain('EUR 100.50');
      expect(lines[4]).not.toContain('EUR 100,50');
    });


    it('should format when formats match', () => {
      const content = `commodity USD
    format $1,000.00

2024-01-01 Test
    expenses:food    $100.50
    assets:checking
`;
      const doc = createDocument(content);
      const parsed = parser.parse(doc);
      const edits = provider.formatDocument(doc, parsed, { tabSize: 2, insertSpaces: true });

      const formatted = edits[0].newText;
      const lines = formatted.split('\n');

      // Should be formatted (line should contain formatted amount)
      expect(lines[4]).toContain('expenses:food');
      expect(lines[4]).toContain('$100.50');
    });
  });

  describe('inferred amounts', () => {
    it('should always format inferred amounts without validation', () => {
      const content = `commodity EUR
    format 1.000,00

2024-01-01 Test
    expenses:food    EUR 100,50
    assets:checking
`;
      const doc = createDocument(content);
      const parsed = parser.parse(doc);
      const edits = provider.formatDocument(doc, parsed, { tabSize: 2, insertSpaces: true });

      const formatted = edits[0].newText;
      const lines = formatted.split('\n');

      // The inferred amount (assets:checking) should always be formatted
      // Verify the line is properly formatted
      expect(lines[5]).toContain('assets:checking');
    });
  });

  describe('mixed validation results', () => {
    it('should format valid lines and preserve invalid lines in same transaction', () => {
      const content = `commodity USD
    format $1,000.00

commodity EUR
    format 1.000,00

2024-01-01 Test
    expenses:food    $50.00
    expenses:travel    EUR 20.50
    assets:checking
`;
      const doc = createDocument(content);
      const parsed = parser.parse(doc);
      const edits = provider.formatDocument(doc, parsed, { tabSize: 2, insertSpaces: true });

      const formatted = edits[0].newText;
      const lines = formatted.split('\n');

      // USD line should be formatted
      const usdLine = lines.find(l => l.includes('expenses:food'));
      expect(usdLine).toContain('$50.00');

      // EUR line should be preserved (decimal mark mismatch)
      const eurLine = lines.find(l => l.includes('expenses:travel'));
      expect(eurLine).toContain('EUR 20.50'); // Original preserved
      expect(eurLine).not.toContain('EUR 20,50'); // Not reformatted
    });
  });

  describe('round-trip validation', () => {
    it('should format correctly when round-trip is safe', () => {
      // This tests a theoretical case where parseAmount and formatAmount
      // might produce different values due to ambiguous formatting
      const content = `2024-01-01 Test
    expenses:food    100
    assets:checking
`;
      const doc = createDocument(content);
      const parsed = parser.parse(doc);
      const edits = provider.formatDocument(doc, parsed, { tabSize: 2, insertSpaces: true });

      const formatted = edits[0].newText;
      // This should work fine for simple cases
      expect(formatted).toContain('expenses:food');
      expect(formatted).toContain('100');
    });
  });

  describe('no commodity declared', () => {
    it('should format normally when commodity is not declared', () => {
      const content = `2024-01-01 Test
    expenses:food    USD 100.5
    assets:checking
`;
      const doc = createDocument(content);
      const parsed = parser.parse(doc);
      const edits = provider.formatDocument(doc, parsed, { tabSize: 2, insertSpaces: true });

      const formatted = edits[0].newText;

      // Should format fine (no declared format to conflict with)
      expect(formatted).toContain('USD 100.5');
    });
  });
});
