/**
 * Formatting validation to prevent data corruption
 *
 * Pure validation functions that check if amounts are safe to format.
 * These functions are used by:
 * 1. Validator class - to generate diagnostics on document change
 * 2. FormattingProvider - to decide whether to skip formatting
 */

import { Posting, ParsedDocument, Amount } from '../types';
import { parseAmount } from '../parser/ast';
import { formatAmount } from '../utils/amountFormatter';
import { FormattingOptions } from '../server/settings';

/**
 * Check if a posting's amount is safe to format
 *
 * @param posting - The posting to validate
 * @param parsedDoc - Full parsed document (for commodity formats)
 * @param settings - Formatting settings
 * @returns true if safe to format, false otherwise
 */
export function isSafeToFormat(
  posting: Posting,
  parsedDoc: ParsedDocument,
  settings?: Partial<FormattingOptions>
): boolean {
  // Skip validation for inferred amounts - they're generated by us, so they're safe
  if (posting.amount?.inferred) {
    return true;
  }

  // No amount to validate
  if (!posting.amount) {
    return true;
  }

  // Run all validation checks
  if (!isAmountRoundTripSafe(posting.amount, parsedDoc, settings)) {
    return false;
  }

  if (!isCommodityFormatMatch(posting.amount, parsedDoc)) {
    return false;
  }

  return true;
}

/**
 * Check if an amount's round-trip is safe
 *
 * Tests: parse → format → parse produces same value
 *
 * @param amount - The amount to validate
 * @param parsedDoc - Full parsed document (for commodity formats)
 * @param settings - Formatting settings
 * @returns true if round-trip is safe, false otherwise
 */
export function isAmountRoundTripSafe(
  amount: Amount,
  parsedDoc: ParsedDocument,
  settings?: Partial<FormattingOptions>
): boolean {
  const commodity = amount.commodity || '';

  // Step 1: Format the parsed amount
  const formattedText = formatAmount(
    amount.quantity,
    commodity,
    parsedDoc,
    settings
  );

  // Step 2: Parse the formatted text back
  const reparsedAmount = parseAmount(formattedText);

  // Step 3: Check if values match
  if (!reparsedAmount) {
    return false; // Cannot parse back
  }

  // Allow small floating point errors (< 0.005 to handle 2 decimal precision)
  const quantityDifference = Math.abs(amount.quantity - reparsedAmount.quantity);
  if (quantityDifference > 0.005) {
    return false; // Value would change
  }

  return true;
}

/**
 * Check if an amount's format matches its declared commodity format
 *
 * @param amount - The amount to validate
 * @param parsedDoc - Full parsed document (for commodity formats)
 * @returns true if formats match (or no declared format), false otherwise
 */
export function isCommodityFormatMatch(
  amount: Amount,
  parsedDoc: ParsedDocument
): boolean {
  if (!amount.commodity) {
    return true; // No commodity to check
  }

  const commodity = parsedDoc.commodities.get(amount.commodity);
  if (!commodity || !commodity.declared || !commodity.format) {
    return true; // No declared format to check against
  }

  const amountFormat = amount.format;
  const declaredFormat = commodity.format;

  // Check if decimal marks match
  if (amountFormat?.decimalMark && declaredFormat.decimalMark) {
    if (amountFormat.decimalMark !== declaredFormat.decimalMark) {
      return false; // Decimal mark mismatch
    }
  }

  // Check if thousands separators match
  if (amountFormat?.thousandsSeparator && declaredFormat.thousandsSeparator) {
    if (amountFormat.thousandsSeparator !== declaredFormat.thousandsSeparator) {
      return false; // Separator mismatch
    }
  }

  return true;
}

/**
 * Get a descriptive reason why an amount is not safe to format
 *
 * This is used by the Validator to generate diagnostic messages
 *
 * @param amount - The amount to check
 * @param parsedDoc - Full parsed document
 * @param settings - Formatting settings
 * @returns Diagnostic message describing the issue, or null if safe
 */
export function getFormatUnsafeReason(
  amount: Amount,
  parsedDoc: ParsedDocument,
  settings?: Partial<FormattingOptions>
): { code: string; message: string } | null {
  const commodity = amount.commodity || '';

  // Check round-trip
  const formattedText = formatAmount(amount.quantity, commodity, parsedDoc, settings);
  const reparsedAmount = parseAmount(formattedText);

  if (!reparsedAmount) {
    return {
      code: 'format-roundtrip-failed',
      message: `Cannot safely format amount: formatted value "${formattedText}" cannot be parsed back`
    };
  }

  const quantityDifference = Math.abs(amount.quantity - reparsedAmount.quantity);
  if (quantityDifference > 0.005) {
    return {
      code: 'format-value-changed',
      message: `Cannot safely format amount: value would change from ${amount.quantity} to ${reparsedAmount.quantity}. This may indicate a format mismatch (e.g., thousand separator vs decimal mark).`
    };
  }

  // Check commodity format match
  if (!amount.commodity) {
    return null; // No commodity to check
  }

  const commodityDef = parsedDoc.commodities.get(amount.commodity);
  if (!commodityDef || !commodityDef.declared || !commodityDef.format) {
    return null; // No declared format to check against
  }

  const amountFormat = amount.format;
  const declaredFormat = commodityDef.format;

  // Check decimal marks
  if (amountFormat?.decimalMark && declaredFormat.decimalMark) {
    if (amountFormat.decimalMark !== declaredFormat.decimalMark) {
      return {
        code: 'format-decimal-mismatch',
        message: `Amount uses decimal mark "${amountFormat.decimalMark}" but commodity ${amount.commodity} is declared with "${declaredFormat.decimalMark}". This may cause value misinterpretation.`
      };
    }
  }

  // Check thousands separators
  if (amountFormat?.thousandsSeparator && declaredFormat.thousandsSeparator) {
    if (amountFormat.thousandsSeparator !== declaredFormat.thousandsSeparator) {
      return {
        code: 'format-separator-mismatch',
        message: `Amount uses thousands separator "${amountFormat.thousandsSeparator}" but commodity ${amount.commodity} is declared with "${declaredFormat.thousandsSeparator}". This may cause formatting issues.`
      };
    }
  }

  return null; // Safe to format
}
